#!/usr/bin/env bash
# =============================================================================
# setup.sh — MeshMonitor Pi First-Boot Setup
# Run once on a fresh Raspberry Pi OS Lite (64-bit) installation.
# Must be run as a user with sudo access (default: pi).
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
ENV_EXAMPLE="${SCRIPT_DIR}/env.example"
DAEMON_JSON="${SCRIPT_DIR}/daemon.json"

# If Docker is installed but we're not in the docker group, relaunch now
# rather than failing silently at the point we first need Docker access.
if command -v docker &>/dev/null && ! docker info &>/dev/null 2>&1; then
  echo "Docker is installed but not accessible — relaunching under 'newgrp docker'..."
  exec newgrp docker <<NEWGRP
    cd "${SCRIPT_DIR}" && bash setup.sh
NEWGRP
fi

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------
info()    { echo -e "\n\e[1;34m[INFO]\e[0m  $*"; }
success() { echo -e "\e[1;32m[OK]\e[0m    $*"; }
warn()    { echo -e "\e[1;33m[WARN]\e[0m  $*"; }
error()   { echo -e "\e[1;31m[ERROR]\e[0m $*" >&2; exit 1; }

prompt() {
  # prompt <variable_name> <display_label> <current_value>
  local var="$1" label="$2" current="$3"
  local input
  echo -en "\n  ${label}"
  [[ -n "$current" ]] && echo -en " \e[2m[${current}]\e[0m"
  echo -en ": "
  read -r input
  if [[ -n "$input" ]]; then
    printf -v "$var" '%s' "$input"
  else
    printf -v "$var" '%s' "$current"
  fi
}

confirm() {
  # confirm <prompt> — returns 0 for yes, 1 for no
  local answer
  echo -en "\n  $* [y/N]: "
  read -r answer
  [[ "${answer,,}" == "y" || "${answer,,}" == "yes" ]]
}

# -----------------------------------------------------------------------------
# Banner
# -----------------------------------------------------------------------------
clear
echo "============================================================"
echo "  MeshMonitor Pi — First-Boot Setup v0.2.4"
echo "  github.com/sfaith/meshmonitor-pi"
echo "============================================================"
echo
echo "  This script will:"
echo "    1. Review and confirm your .env settings"
echo "    2. Install Docker (if not present)"
echo "    3. Harden the OS for SD card longevity"
echo "    4. Configure Docker daemon log limits"
echo "    5. Enable hardware watchdog (auto-reboot on hang)"
echo "    6. Install systemd boot service (stack starts on power-on)"
echo "    7. Pull images and start the stack"
echo
echo "  Press Ctrl+C at any time to abort."

# -----------------------------------------------------------------------------
# Step 1 — Load and confirm .env settings
# -----------------------------------------------------------------------------
info "Step 1/7 — Environment Configuration"

# Seed from env.example if .env doesn't exist yet
if [[ ! -f "$ENV_FILE" ]]; then
  if [[ ! -f "$ENV_EXAMPLE" ]]; then
    error "env.example not found in ${SCRIPT_DIR}. Cannot continue."
  fi
  cp "$ENV_EXAMPLE" "$ENV_FILE"
  warn ".env not found — created from env.example. Please fill in your values."
fi

# Source current values
set +u
# shellcheck disable=SC1090
source "$ENV_FILE"
set -u

echo
echo "  Current settings (press Enter to keep, or type a new value):"

prompt PI_IP               "Pi static IP address  " "${PI_IP:-}"
prompt HOST_PORT           "MeshMonitor port      " "${HOST_PORT:-8080}"
prompt SESSION_SECRET      "Session secret        " "${SESSION_SECRET:-}"
prompt MESHTASTIC_NODE_IP  "Meshtastic node IP    " "${MESHTASTIC_NODE_IP:-}"
prompt MESHTASTIC_NODE_PORT "Meshtastic port      " "${MESHTASTIC_NODE_PORT:-4403}"
prompt TZ                  "Timezone              " "${TZ:-America/Phoenix}"
prompt UPGRADE_TIME        "Auto-upgrade time     " "${UPGRADE_TIME:-03:00}"

# Derive ALLOWED_ORIGINS from PI_IP and HOST_PORT
ALLOWED_ORIGINS="http://${PI_IP}:${HOST_PORT}"

echo
echo "  ── Derived settings ──────────────────────────────────"
echo "  ALLOWED_ORIGINS : ${ALLOWED_ORIGINS}"
echo "  ──────────────────────────────────────────────────────"

# Validate required fields
[[ -z "${PI_IP:-}" ]]          && error "PI_IP is required."
[[ -z "${SESSION_SECRET:-}" ]] && error "SESSION_SECRET is required. Generate with: openssl rand -hex 32"
[[ "${SESSION_SECRET}" == "REPLACE_WITH_SECURE_RANDOM_STRING" ]] && \
  error "SESSION_SECRET has not been changed from the placeholder. Generate with: openssl rand -hex 32"

# Write confirmed values back to .env
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date)
# Do not commit this file to git.

PI_IP=${PI_IP}
HOST_PORT=${HOST_PORT}
ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
TRUST_PROXY=false
COOKIE_SECURE=false
SESSION_SECRET=${SESSION_SECRET}

MESHTASTIC_NODE_IP=${MESHTASTIC_NODE_IP}
MESHTASTIC_NODE_PORT=${MESHTASTIC_NODE_PORT}

TZ=${TZ}

UPGRADE_TIME=${UPGRADE_TIME:-03:00}

# SERIAL_DEVICE=/dev/ttyACM0
EOF

success ".env written."

# -----------------------------------------------------------------------------
# Step 2 — Install Docker
# -----------------------------------------------------------------------------
info "Step 2/7 — Docker Installation"

if command -v docker &>/dev/null; then
  DOCKER_VER=$(docker --version)
  success "Docker already installed: ${DOCKER_VER}"
else
  if ! confirm "Docker not found. Install now using the official script?
    NOTE: Uses get.docker.com — the official, Pi-supported install method.
    Recommended: y"; then
    error "Docker is required. Aborting."
  fi
  info "Downloading and running Docker install script..."
  curl -fsSL https://get.docker.com | sudo sh
  sudo usermod -aG docker "${USER}"
  success "Docker installed."
  warn "Docker group membership requires a new shell session."
  warn "Relaunching setup under 'newgrp docker' to continue..."
  exec newgrp docker <<NEWGRP
    cd "${SCRIPT_DIR}" && bash setup.sh
NEWGRP
fi

# Verify docker compose v2
if ! docker compose version &>/dev/null; then
  error "Docker Compose v2 not found. Ensure Docker Engine >= 23 is installed."
fi
success "Docker Compose v2 confirmed."

# -----------------------------------------------------------------------------
# Step 3 — OS hardening for SD card longevity
# -----------------------------------------------------------------------------
info "Step 3/7 — SD Card Write Minimization"

# 3a. noatime on root partition
if grep -q 'noatime' /etc/fstab; then
  success "noatime already set in /etc/fstab."
else
  if confirm "Add 'noatime' mount option to root partition in /etc/fstab?
    NOTE: Stops the filesystem writing an access timestamp on every file read.
          Reduces SD card writes with no impact on normal operation.
    Recommended: y"; then
    sudo sed -i 's|\(PARTUUID=[^ ]*\s\+/\s\+ext4\s\+\)\(defaults\)|\1defaults,noatime|' /etc/fstab
    success "noatime added to /etc/fstab (takes effect on next reboot)."
  else
    warn "Skipped noatime. SD card will receive extra writes on every file read."
  fi
fi

# 3b. Volatile systemd journal (RAM only)
JOURNAL_CONF="/etc/systemd/journald.conf.d/volatile.conf"
if [[ -f "$JOURNAL_CONF" ]]; then
  success "Volatile journal already configured."
else
  if confirm "Configure systemd journal as volatile (RAM only, lost on reboot)?
    NOTE: System logs (SSH logins, service events) are stored in RAM and lost
          on reboot. This is fine for a dedicated appliance — MeshMonitor's
          own data is unaffected and persists normally in the Docker volume.
    Recommended: y"; then
    sudo mkdir -p /etc/systemd/journald.conf.d
    sudo tee "$JOURNAL_CONF" > /dev/null <<'JEOF'
# MeshMonitor Pi — volatile journal to minimize SD card writes
[Journal]
Storage=volatile
RuntimeMaxUse=32M
JEOF
    sudo systemctl restart systemd-journald
    success "Volatile journal configured."
  else
    warn "Skipped volatile journal. System logs will continue writing to SD."
  fi
fi

# 3c. tmpfs for /var/log
if grep -q 'tmpfs.*/var/log' /etc/fstab; then
  success "tmpfs /var/log already in /etc/fstab."
else
  if confirm "Mount /var/log as tmpfs (RAM, 64MB, lost on reboot)?
    NOTE: Redirects all system log files to RAM. Complements the volatile
          journal above. Frees the SD card from continuous log writes.
          64MB is ample — typical usage is under 5MB.
    Recommended: y"; then
    echo "tmpfs  /var/log  tmpfs  defaults,noatime,size=64m  0  0" | sudo tee -a /etc/fstab > /dev/null
    warn "/var/log tmpfs will take effect on next reboot."
    success "tmpfs /var/log added to /etc/fstab."
  else
    warn "Skipped tmpfs /var/log."
  fi
fi

# -----------------------------------------------------------------------------
# Step 4 — Docker daemon log limits
# -----------------------------------------------------------------------------
info "Step 4/7 — Docker Daemon Configuration"

DOCKER_DAEMON="/etc/docker/daemon.json"

if [[ -f "$DOCKER_DAEMON" ]]; then
  warn "${DOCKER_DAEMON} already exists:"
  cat "$DOCKER_DAEMON"
  if ! confirm "Overwrite with MeshMonitor Pi log limits?
    NOTE: The existing file will be replaced with the daemon.json from this repo.
          Answer n if you have custom Docker daemon settings you want to keep.
          Per-service log limits in docker-compose.yml apply regardless.
    Recommended: n (if contents match above), y (if different)"; then
    warn "Skipped daemon.json update. Per-service log limits in docker-compose.yml still apply."
  else
    sudo cp "$DAEMON_JSON" "$DOCKER_DAEMON"
    sudo systemctl restart docker
    success "daemon.json updated and Docker restarted."
  fi
else
  sudo mkdir -p /etc/docker
  sudo cp "$DAEMON_JSON" "$DOCKER_DAEMON"
  sudo systemctl restart docker
  success "daemon.json installed. System-wide Docker log limits active."
fi

# -----------------------------------------------------------------------------
# Step 5 — Hardware watchdog
# -----------------------------------------------------------------------------
info "Step 5/7 — Hardware Watchdog"

# On Raspberry Pi OS Bookworm, systemd automatically claims /dev/watchdog at
# boot and pets it as long as PID 1 is healthy. This is strictly better than
# the userspace watchdog daemon — it catches kernel panics and init freezes.
# We detect which approach is in use and configure accordingly.

WATCHDOG_HANDLED=false

# Check if systemd already owns the watchdog (Bookworm default behaviour).
# fuser /dev/watchdog0 returns PID 1 (systemd) if it holds the device open.
# This is the most reliable detection method — direct kernel state, no log parsing.
WATCHDOG_OWNER=$(sudo fuser /dev/watchdog0 2>/dev/null | tr -d ' ' || true)
if [[ "$WATCHDOG_OWNER" == "1" ]]; then
  success "Hardware watchdog active — managed by systemd (Broadcom BCM2835)."
  WATCHDOG_HANDLED=true

  # Ensure dtparam=watchdog=on is in config.txt so it persists across reboots
  if grep -q 'dtparam=watchdog=on' /boot/firmware/config.txt 2>/dev/null; then
    success "dtparam=watchdog=on already set in /boot/firmware/config.txt."
  else
    echo "dtparam=watchdog=on" | sudo tee -a /boot/firmware/config.txt > /dev/null
    success "dtparam=watchdog=on added to /boot/firmware/config.txt."
  fi

  # Disable the userspace watchdog daemon if still present — systemd holds
  # /dev/watchdog exclusively so the daemon can't open it anyway (errno 16)
  # and leaves misleading "cannot open /dev/watchdog" errors in the journal.
  WATCHDOG_ENABLED=false
  systemctl is-enabled watchdog 2>/dev/null | grep -q "enabled" && WATCHDOG_ENABLED=true || true
  if [[ "$WATCHDOG_ENABLED" == "true" ]]; then
    warn "Disabling redundant userspace watchdog daemon (systemd handles this natively on Bookworm)."
    sudo systemctl stop watchdog 2>/dev/null || true
    sudo systemctl disable watchdog 2>/dev/null || true
    success "Userspace watchdog daemon disabled."
  fi
fi

# Fall back to userspace watchdog daemon if systemd isn't handling it
if [[ "$WATCHDOG_HANDLED" == "false" ]]; then
  if systemctl is-active --quiet watchdog 2>/dev/null; then
    success "Userspace watchdog daemon already active."
  else
    if confirm "Enable hardware watchdog (auto-reboot on system hang)?
    NOTE: Uses the Pi's built-in hardware watchdog chip. If the OS freezes
          completely (kernel panic, memory corruption, etc.) the Pi will
          automatically hard-reboot — no human intervention needed.
          Has no effect during normal operation.
    Recommended: y"; then
      # Ensure dtparam=watchdog=on is set
      if ! grep -q 'dtparam=watchdog=on' /boot/firmware/config.txt 2>/dev/null; then
        echo "dtparam=watchdog=on" | sudo tee -a /boot/firmware/config.txt > /dev/null
        success "dtparam=watchdog=on added to /boot/firmware/config.txt."
      fi

      # Install and configure userspace watchdog daemon
      if ! command -v watchdog &>/dev/null; then
        sudo apt-get install -y watchdog
      fi
      sudo tee /etc/watchdog.conf > /dev/null <<'WEOF'
# MeshMonitor Pi — hardware watchdog configuration
watchdog-device = /dev/watchdog
watchdog-timeout = 15
interval = 5
max-load-1 = 24
WEOF
      echo 'bcm2835_wdt' | sudo tee /etc/modules-load.d/bcm2835_wdt.conf > /dev/null
      sudo systemctl enable watchdog
      sudo systemctl start watchdog
      success "Hardware watchdog daemon enabled."
    else
      warn "Skipped hardware watchdog."
    fi
  fi
fi

# -----------------------------------------------------------------------------
# Step 6 — systemd boot service
# -----------------------------------------------------------------------------
info "Step 6/7 — systemd Boot Service"

# Ensures the stack starts on every boot, even after a watchdog-triggered
# hard reboot where Docker's own restart policy may not fire cleanly.

SYSTEMD_UNIT="/etc/systemd/system/meshmonitor.service"

if [[ -f "$SYSTEMD_UNIT" ]]; then
  success "meshmonitor.service already installed."
else
  if confirm "Install systemd service to start stack automatically on boot?
    NOTE: Ensures the MeshMonitor stack starts on every boot — including after
          a watchdog-triggered hard reboot or power outage. Without this the
          stack may not restart if Docker didn't shut down cleanly.
    Recommended: y"; then
    sudo tee "$SYSTEMD_UNIT" > /dev/null <<SEOF
[Unit]
Description=MeshMonitor Pi Stack
Requires=docker.service
After=docker.service network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
# WorkingDirectory is set to the repo path at install time.
# If you move the repo, re-run setup.sh to update this unit.
WorkingDirectory=${SCRIPT_DIR}
ExecStart=/usr/bin/docker compose up -d
ExecStop=/usr/bin/docker compose down
TimeoutStartSec=120

[Install]
WantedBy=multi-user.target
SEOF
    sudo systemctl daemon-reload
    sudo systemctl enable meshmonitor.service
    success "meshmonitor.service installed and enabled."
  else
    warn "Skipped systemd service. Stack will not auto-start on reboot."
  fi
fi

# 6b. Auto-upgrade cron job
CRON_MARKER="meshmonitor-pi auto-upgrade"
CRON_INSTALLED=false
crontab -l 2>/dev/null | grep -q "$CRON_MARKER" && CRON_INSTALLED=true || true

if [[ "$CRON_INSTALLED" == "true" ]]; then
  success "Auto-upgrade cron job already installed."
else
  if confirm "Install daily auto-upgrade cron job (pulls new images at ${UPGRADE_TIME:-03:00})?
    NOTE: Runs 'docker compose pull && docker compose up -d' daily on a schedule.
          Logs to /tmp/meshmonitor-upgrade.log (RAM only, lost on reboot).
    Recommended: y"; then
    UPGRADE_HOUR=$(echo "${UPGRADE_TIME:-03:00}" | cut -d: -f1)
    UPGRADE_MIN=$(echo "${UPGRADE_TIME:-03:00}"  | cut -d: -f2)
    CRON_LINE="${UPGRADE_MIN} ${UPGRADE_HOUR} * * * cd ${SCRIPT_DIR} && docker compose pull && docker compose up -d >> /tmp/meshmonitor-upgrade.log 2>&1 # ${CRON_MARKER}"
    ( crontab -l 2>/dev/null; echo "$CRON_LINE" ) | crontab -
    success "Auto-upgrade cron job installed (daily at ${UPGRADE_TIME:-03:00})."
  else
    warn "Skipped auto-upgrade cron. Upgrade manually with: docker compose pull && docker compose up -d"
  fi
fi

# -----------------------------------------------------------------------------
# Step 7 — Pull images and start stack
# -----------------------------------------------------------------------------
info "Step 7/7 — Start MeshMonitor Stack"

cd "$SCRIPT_DIR"

if confirm "Pull latest images and start the stack now?
    NOTE: Pulls the latest MeshMonitor image and starts the stack.
          Safe to run on re-runs — skips pull if image is current,
          and leaves a running stack untouched if already healthy.
    Recommended: y"; then
  docker compose pull
  docker compose up -d
  echo
  success "Stack started!"
  echo
  echo "  ── Access ────────────────────────────────────────────"
  echo "  Web UI  : http://${PI_IP}:${HOST_PORT}"
  echo "  Login   : admin / changeme  (change immediately!)"
  echo "  ──────────────────────────────────────────────────────"
  echo
  echo "  Useful commands:"
  echo "    docker compose logs -f                        # live logs"
  echo "    docker compose ps                             # container status"
  echo "    docker compose down                           # stop stack"
  echo "    docker compose pull && docker compose up -d  # manual upgrade"
else
  warn "Stack not started. Run manually with:"
  echo "    cd ${SCRIPT_DIR} && docker compose up -d"
fi

echo
echo "============================================================"
echo "  Setup complete."
echo "  IMPORTANT: Reboot for /etc/fstab changes to take effect."
echo "    sudo reboot"
echo "============================================================"
echo
