#!/usr/bin/env bash
# =============================================================================
# setup.sh — MeshMonitor Pi First-Boot Setup
# Run once on a fresh Raspberry Pi OS Lite (64-bit) installation.
# Must be run as a user with sudo access (default: pi).
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
ENV_EXAMPLE="${SCRIPT_DIR}/env.example"
DAEMON_JSON="${SCRIPT_DIR}/daemon.json"

# If Docker is installed but we're not in the docker group, relaunch now
# rather than failing silently at the point we first need Docker access.
if command -v docker &>/dev/null && ! docker info &>/dev/null 2>&1; then
  echo "Docker is installed but not accessible — relaunching under 'newgrp docker'..."
  exec newgrp docker <<NEWGRP
    cd "${SCRIPT_DIR}" && bash setup.sh
NEWGRP
fi

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------
info()    { echo -e "\n\e[1;34m[INFO]\e[0m  $*"; }
success() { echo -e "\e[1;32m[OK]\e[0m    $*"; }
warn()    { echo -e "\e[1;33m[WARN]\e[0m  $*"; }
error()   { echo -e "\e[1;31m[ERROR]\e[0m $*" >&2; exit 1; }

prompt() {
  # prompt <variable_name> <display_label> <current_value>
  local var="$1" label="$2" current="$3"
  local input
  echo -en "\n  ${label}"
  [[ -n "$current" ]] && echo -en " \e[2m[${current}]\e[0m"
  echo -en ": "
  read -r input
  if [[ -n "$input" ]]; then
    printf -v "$var" '%s' "$input"
  else
    printf -v "$var" '%s' "$current"
  fi
}

confirm() {
  # confirm <prompt> — returns 0 for yes, 1 for no
  local answer
  echo -en "\n  $* [y/N]: "
  read -r answer
  [[ "${answer,,}" == "y" || "${answer,,}" == "yes" ]]
}

# -----------------------------------------------------------------------------
# Banner
# -----------------------------------------------------------------------------
clear
echo "============================================================"
echo "  MeshMonitor Pi — First-Boot Setup v0.1.2"
echo "  github.com/sfaith/meshmonitor-pi"
echo "============================================================"
echo
echo "  This script will:"
echo "    1. Review and confirm your .env settings"
echo "    2. Install Docker (if not present)"
echo "    3. Harden the OS for SD card longevity"
echo "    4. Configure Docker daemon log limits"
echo "    5. Enable hardware watchdog (auto-reboot on hang)"
echo "    6. Install systemd boot service (stack starts on power-on)"
echo "    7. Pull images and start the stack"
echo
echo "  Press Ctrl+C at any time to abort."

# -----------------------------------------------------------------------------
# Step 1 — Load and confirm .env settings
# -----------------------------------------------------------------------------
info "Step 1/7 — Environment Configuration"

# Seed from env.example if .env doesn't exist yet
if [[ ! -f "$ENV_FILE" ]]; then
  if [[ ! -f "$ENV_EXAMPLE" ]]; then
    error "env.example not found in ${SCRIPT_DIR}. Cannot continue."
  fi
  cp "$ENV_EXAMPLE" "$ENV_FILE"
  warn ".env not found — created from env.example. Please fill in your values."
fi

# Source current values
set +u
# shellcheck disable=SC1090
source "$ENV_FILE"
set -u

echo
echo "  Current settings (press Enter to keep, or type a new value):"

prompt PI_IP               "Pi static IP address  " "${PI_IP:-}"
prompt HOST_PORT           "MeshMonitor port      " "${HOST_PORT:-8080}"
prompt SESSION_SECRET      "Session secret        " "${SESSION_SECRET:-}"
prompt MESHTASTIC_NODE_IP  "Meshtastic node IP    " "${MESHTASTIC_NODE_IP:-10.45.72.250}"
prompt MESHTASTIC_NODE_PORT "Meshtastic port      " "${MESHTASTIC_NODE_PORT:-4403}"
prompt TZ                  "Timezone              " "${TZ:-America/Phoenix}"
prompt MQTT_BROKER         "MQTT broker           " "${MQTT_BROKER:-mqtt.meshtastic.org}"
prompt MQTT_TOPIC          "MQTT topic            " "${MQTT_TOPIC:-msh/US/2/e/LongFast/#}"
prompt WATCHTOWER_SCHEDULE "Watchtower schedule   " "${WATCHTOWER_SCHEDULE:-0 0 3 * * *}"

# Derive ALLOWED_ORIGINS from PI_IP and HOST_PORT
ALLOWED_ORIGINS="http://${PI_IP}:${HOST_PORT}"

echo
echo "  ── Derived settings ──────────────────────────────────"
echo "  ALLOWED_ORIGINS : ${ALLOWED_ORIGINS}"
echo "  ──────────────────────────────────────────────────────"

# Validate required fields
[[ -z "${PI_IP:-}" ]]          && error "PI_IP is required."
[[ -z "${SESSION_SECRET:-}" ]] && error "SESSION_SECRET is required. Generate with: openssl rand -hex 32"
[[ "${SESSION_SECRET}" == "REPLACE_WITH_SECURE_RANDOM_STRING" ]] && \
  error "SESSION_SECRET has not been changed from the placeholder. Generate with: openssl rand -hex 32"

# Write confirmed values back to .env
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date)
# Do not commit this file to git.

PI_IP=${PI_IP}
HOST_PORT=${HOST_PORT}
ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
TRUST_PROXY=false
COOKIE_SECURE=false
SESSION_SECRET=${SESSION_SECRET}

MESHTASTIC_NODE_IP=${MESHTASTIC_NODE_IP}
MESHTASTIC_NODE_PORT=${MESHTASTIC_NODE_PORT}

TZ=${TZ}

MQTT_BROKER=${MQTT_BROKER}
MQTT_PORT=${MQTT_PORT:-1883}
MQTT_USERNAME=${MQTT_USERNAME:-meshdev}
MQTT_PASSWORD=${MQTT_PASSWORD:-large4cats}
MQTT_TOPIC=${MQTT_TOPIC}

WATCHTOWER_SCHEDULE="${WATCHTOWER_SCHEDULE}"

# SERIAL_DEVICE=/dev/ttyACM0
EOF

success ".env written."

# -----------------------------------------------------------------------------
# Step 2 — Install Docker
# -----------------------------------------------------------------------------
info "Step 2/7 — Docker Installation"

if command -v docker &>/dev/null; then
  DOCKER_VER=$(docker --version)
  success "Docker already installed: ${DOCKER_VER}"
else
  if ! confirm "Docker not found. Install now using the official script?
    NOTE: Uses get.docker.com — the official, Pi-supported install method.
    Recommended: y"; then
    error "Docker is required. Aborting."
  fi
  info "Downloading and running Docker install script..."
  curl -fsSL https://get.docker.com | sudo sh
  sudo usermod -aG docker "${USER}"
  success "Docker installed."
  warn "Docker group membership requires a new shell session."
  warn "Relaunching setup under 'newgrp docker' to continue..."
  exec newgrp docker <<NEWGRP
    cd "${SCRIPT_DIR}" && bash setup.sh
NEWGRP
fi

# Verify docker compose v2
if ! docker compose version &>/dev/null; then
  error "Docker Compose v2 not found. Ensure Docker Engine >= 23 is installed."
fi
success "Docker Compose v2 confirmed."

# -----------------------------------------------------------------------------
# Step 3 — OS hardening for SD card longevity
# -----------------------------------------------------------------------------
info "Step 3/7 — SD Card Write Minimization"

# 3a. noatime on root partition
if grep -q 'noatime' /etc/fstab; then
  success "noatime already set in /etc/fstab."
else
  if confirm "Add 'noatime' mount option to root partition in /etc/fstab?
    NOTE: Stops the filesystem writing an access timestamp on every file read.
          Reduces SD card writes with no impact on normal operation.
    Recommended: y"; then
    sudo sed -i 's|\(PARTUUID=[^ ]*\s\+/\s\+ext4\s\+\)\(defaults\)|\1defaults,noatime|' /etc/fstab
    success "noatime added to /etc/fstab (takes effect on next reboot)."
  else
    warn "Skipped noatime. SD card will receive extra writes on every file read."
  fi
fi

# 3b. Volatile systemd journal (RAM only)
JOURNAL_CONF="/etc/systemd/journald.conf.d/volatile.conf"
if [[ -f "$JOURNAL_CONF" ]]; then
  success "Volatile journal already configured."
else
  if confirm "Configure systemd journal as volatile (RAM only, lost on reboot)?
    NOTE: System logs (SSH logins, service events) are stored in RAM and lost
          on reboot. This is fine for a dedicated appliance — MeshMonitor's
          own data is unaffected and persists normally in the Docker volume.
    Recommended: y"; then
    sudo mkdir -p /etc/systemd/journald.conf.d
    sudo tee "$JOURNAL_CONF" > /dev/null <<'JEOF'
# MeshMonitor Pi — volatile journal to minimize SD card writes
[Journal]
Storage=volatile
RuntimeMaxUse=32M
JEOF
    sudo systemctl restart systemd-journald
    success "Volatile journal configured."
  else
    warn "Skipped volatile journal. System logs will continue writing to SD."
  fi
fi

# 3c. tmpfs for /var/log
if grep -q 'tmpfs.*/var/log' /etc/fstab; then
  success "tmpfs /var/log already in /etc/fstab."
else
  if confirm "Mount /var/log as tmpfs (RAM, 64MB, lost on reboot)?
    NOTE: Redirects all system log files to RAM. Complements the volatile
          journal above. Frees the SD card from continuous log writes.
          64MB is ample — typical usage is under 5MB.
    Recommended: y"; then
    echo "tmpfs  /var/log  tmpfs  defaults,noatime,size=64m  0  0" | sudo tee -a /etc/fstab > /dev/null
    warn "/var/log tmpfs will take effect on next reboot."
    success "tmpfs /var/log added to /etc/fstab."
  else
    warn "Skipped tmpfs /var/log."
  fi
fi

# -----------------------------------------------------------------------------
# Step 4 — Docker daemon log limits
# -----------------------------------------------------------------------------
info "Step 4/7 — Docker Daemon Configuration"

DOCKER_DAEMON="/etc/docker/daemon.json"

if [[ -f "$DOCKER_DAEMON" ]]; then
  warn "${DOCKER_DAEMON} already exists:"
  cat "$DOCKER_DAEMON"
  if ! confirm "Overwrite with MeshMonitor Pi log limits?"; then
    warn "Skipped daemon.json update. Per-service log limits in docker-compose.yml still apply."
  else
    sudo cp "$DAEMON_JSON" "$DOCKER_DAEMON"
    sudo systemctl restart docker
    success "daemon.json updated and Docker restarted."
  fi
else
  sudo mkdir -p /etc/docker
  sudo cp "$DAEMON_JSON" "$DOCKER_DAEMON"
  sudo systemctl restart docker
  success "daemon.json installed. System-wide Docker log limits active."
fi

# -----------------------------------------------------------------------------
# Step 5 — Hardware watchdog
# -----------------------------------------------------------------------------
info "Step 5/7 — Hardware Watchdog"

# The Pi 4 has a built-in hardware watchdog (bcm2835_wdt).
# If the OS hangs and stops petting the watchdog, the Pi hard-reboots.
# This catches full system freezes that no software monitor can recover from.

if systemctl is-active --quiet watchdog 2>/dev/null; then
  success "Hardware watchdog already active."
else
  if confirm "Enable hardware watchdog (auto-reboot on system hang)?
    NOTE: Uses the Pi 4's built-in hardware watchdog chip. If the OS freezes
          completely (kernel panic, memory corruption, etc.) the Pi will
          automatically hard-reboot after 15 seconds — no human intervention
          needed. Has no effect during normal operation.
    Recommended: y"; then
    # Install watchdog daemon if needed
    if ! command -v watchdog &>/dev/null; then
      sudo apt-get install -y watchdog
    fi

    # Configure watchdog
    sudo tee /etc/watchdog.conf > /dev/null <<'WEOF'
# MeshMonitor Pi — hardware watchdog configuration
watchdog-device = /dev/watchdog
watchdog-timeout = 15
interval = 5
max-load-1 = 24
WEOF

    # Enable the kernel module and service
    sudo modprobe bcm2835_wdt
    echo 'bcm2835_wdt' | sudo tee /etc/modules-load.d/bcm2835_wdt.conf > /dev/null
    sudo systemctl enable watchdog
    sudo systemctl start watchdog
    success "Hardware watchdog enabled. Pi will auto-reboot if OS hangs."
  else
    warn "Skipped hardware watchdog."
  fi
fi

# -----------------------------------------------------------------------------
# Step 6 — systemd boot service
# -----------------------------------------------------------------------------
info "Step 6/7 — systemd Boot Service"

# Ensures the stack starts on every boot, even after a watchdog-triggered
# hard reboot where Docker's own restart policy may not fire cleanly.

SYSTEMD_UNIT="/etc/systemd/system/meshmonitor.service"

if [[ -f "$SYSTEMD_UNIT" ]]; then
  success "meshmonitor.service already installed."
else
  if confirm "Install systemd service to start stack automatically on boot?
    NOTE: Ensures the MeshMonitor stack starts on every boot — including after
          a watchdog-triggered hard reboot or power outage. Without this the
          stack may not restart if Docker didn't shut down cleanly.
    Recommended: y"; then
    sudo tee "$SYSTEMD_UNIT" > /dev/null <<SEOF
[Unit]
Description=MeshMonitor Pi Stack
Requires=docker.service
After=docker.service network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${SCRIPT_DIR}
ExecStart=/usr/bin/docker compose up -d
ExecStop=/usr/bin/docker compose down
TimeoutStartSec=120

[Install]
WantedBy=multi-user.target
SEOF
    sudo systemctl daemon-reload
    sudo systemctl enable meshmonitor.service
    success "meshmonitor.service installed and enabled."
  else
    warn "Skipped systemd service. Stack will not auto-start on reboot."
  fi
fi

# -----------------------------------------------------------------------------
# Step 7 — Pull images and start stack
# -----------------------------------------------------------------------------
info "Step 7/7 — Start MeshMonitor Stack"

cd "$SCRIPT_DIR"

if confirm "Pull latest images and start the stack now?
    NOTE: Downloads MeshMonitor, mqtt-proxy, and Watchtower images (~500MB).
          Requires internet access. The stack will start automatically on
          future reboots via the systemd service installed in step 6.
    Recommended: y"; then
  docker compose pull
  docker compose up -d
  echo
  success "Stack started!"
  echo
  echo "  ── Access ────────────────────────────────────────────"
  echo "  Web UI  : http://${PI_IP}:${HOST_PORT}"
  echo "  Login   : admin / changeme  (change immediately!)"
  echo "  ──────────────────────────────────────────────────────"
  echo
  echo "  Useful commands:"
  echo "    docker compose logs -f                        # live logs"
  echo "    docker compose ps                             # container status"
  echo "    docker compose down                           # stop stack"
  echo "    docker compose pull && docker compose up -d  # manual upgrade"
else
  warn "Stack not started. Run manually with:"
  echo "    cd ${SCRIPT_DIR} && docker compose up -d"
fi

echo
echo "============================================================"
echo "  Setup complete."
echo "  IMPORTANT: Reboot for /etc/fstab changes to take effect."
echo "    sudo reboot"
echo "============================================================"
echo
